apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo1
  name: demo1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: loadBalancer
  strategy: {}
  template:
    metadata:
      labels:
        app: loadBalancer
    spec:
      containers:
        - image: nginx
          name: nginx