apiVersion: batch/v1
kind: CronJob
metadata:
  name: schedule-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        metadata:
          name: ubuntu-print
        spec:
          containers:
          - name: ubuntu-print
            image: ubuntu
            command: ["/bin/echo"]
            args: ["Hello"]
          restartPolicy: Never

