apiVersion: batch/v1
kind: Job
metadata:
  name: myjob1
spec:
  completions: 9
  parallelism: 3
  template:
    metadata:
      name: myjob1
    spec:
      containers:
      - name: myjob1
        image: ubuntu
        command: ["/bin/sh"]
        args: ["-c", "sleep 3"]
      restartPolicy: Never