apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec:
  containers:
  - name: httpd-container
    image: httpd
    env:
    - name: MONGO_HOST
      valueFrom:
        secretKeyRef:
          name: dbsecret
          key: db_host
    - name: MONGO_USER
      valueFrom:
        secretKeyRef:
          name: dbsecret
          key: db_user
    - name: MONGO_PASS
      valueFrom:
        secretKeyRef:
          name: dbsecret
          key: db_pass
    envFrom:
      - secretRef: 
          name: gamesecret
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
