apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo2
  name: demo2
spec:
  containers:
  - image: docker.io/nginx
    name: demo1
    securityContext:
     runAsNonRoot: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
