apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources-count
  namespace: demo
spec:
  hard:
    configmaps: "10"
    persistentvolumeclaims: "4"
    pods: "1"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"