######### kubectl create -f pod-defination.yaml ############################
apiVersion: v1
kind: Pod
metadata: 
  name: pod2
  namespace: demo
  labels:
    type: frontend
spec:
  containers:
    - name: httpd-container
      image: httpd
      resources:
        requests:
          memory: 2Gi
          cpu: 1
        limits:
          memory: 1Gi
          cpu: 1