apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-accessor
  name: secret-accessor
spec:
  serviceAccountName: secret-manager
  containers:
  - image: nginx
    name: secret-accessor
    resources: {}
      