apiVersion: v1
kind: Pod
metadata:
  name: httpd-tolerated-pod
spec:
  containers:
  - name: httpd
    image: httpd
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"

