apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
  labels:
    type: frontend
spec:
  selector:
    matchLabels:
      type: frontend
      release: blue-green
      version: blue
  replicas: 3
  template:
    metadata:
      name: mywebapp
      labels:
        type: frontend
        release: blue-green
        version: blue
    spec:
      containers:
        - name: mywebapp
          image: navjoy220161/node-mongo:blue

