apiVersion: v1
kind: Service
metadata:
  name: blue-service
spec:
  type: NodePort
  selector:
    type: frontend
    release: blue-green
    version: blue
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 31000
