apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      type: frontend
      release: blue-green
      version: green
  template:
    metadata:
      name: nodeapp-pod
      labels:
        type: frontend
        release: blue-green
        version: blue
    spec:
      containers:
      - name: nodeapp-container
        image: navjoy220161/node-mongo:green
        envFrom:
        - configMapRef:
          name: app-config-new