apiVersion: v1
kind: Service
metadata:
  name: green-service
spec:
  type: LoadBalancer
  selector:
    type: frontend
    release: blue-green
    version: green
  ports:
  - port: 80
    targetPort: 3000
