apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
spec:
  containers:
  - name: busybox
    image: busybox
    args:
      - sh
      - -c
      - sleep 30; touch hello; sleep 20; rm -f hello; sleep 600
    readinessProbe:
      exec:
        command:
          - cat 
          - hello
      initialDelaySeconds: 5
      periodSeconds: 3
      failureThreshold: 3
