apiVersion: v1
kind: Pod
metadata:
  name: mysecret
spec:
  containers:
    - name: secretpod
      image: httpd
      resources:
        limits:
          cpu: 1
          memory: "1Gi"
      envFrom:
        - secretRef:
            name: my-secret
      env:
       - name: ENEMY_TYPE
         valueFrom:
            secretKeyRef:
              name: gameui
              key: ENEMIES
      

         