apiVersion: v1
kind: Pod
metadata:
  name: mysecret1-pod
spec:
  containers:
    - name: secretpod
      image: nginx
      volumeMounts:
        # name must match the volume name below
        - name: app-secret-volume
          mountPath: /etc/secret-volume
  volumes:
    - name: app-secret-volume
      secret: 
        secretName: my-secret
         