apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo3
  name: demo3
spec:
  containers:
  - args:
    - sleep
    - "100000"
    image: busybox
    name: demo3
    resources: {}
    securityContext:
     runAsNonRoot: true
