apiVersion: v1
kind: Pod
metadata:
  labels:
    run: privileged
  name: privileged
spec:
  containers:
  - args:
    - sleep
    - "100000"
    image: busybox
    name: privileged
    resources: {}
    securityContext:
     privileged: true
