######### kubectl create -f pod-defination.yaml ############################
apiVersion: v1
kind: Pod
metadata: 
  name: backend
  labels:
    type: backend
spec:
  containers:
    - name: nginx-container
      image: nginx