apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      name: mongodb-pod
      labels:
        type: backend
    spec:
      containers:
      - name: mongo
        image: mongo:5.0.15
