apiVersion: v1
kind: Pod
metadata:
  name: pod2-with-anti-affinity
spec:
  affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: type
                operator: In
                values:
                - frontend
            topologyKey: "gpu"
  containers:
  - name: with-pod-anti-affinity
    image: mongo