apiVersion: v1
kind: Pod
metadata:
  name: my-frontend-pod
  labels:
    type: frontend
spec:
  containers:
    - name: httpd
      image: httpd
  affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu
                operator: Exists
