apiVersion: v1
kind: Pod
metadata:
  name: pod1-with-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: type
            operator: In
            values:
            - frontend
        topologyKey: gpu
  containers:
  - name: with-pod-affinity
    image: redis