apiVersion: v1
kind: Pod
metadata:
  name: pod-security-context
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu
      command: ["sleep","120"]
      securityContext:
        runAsUser: 1000
        capabilities: 
          add: ["MAC_ADMIN"]