apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongodb-h"
  replicas: 2
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      name: mongodb-pod
      labels:
        type: backend
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongo-pvc2
  volumeClaimTemplates:
  - metadata:
      name: mongo-pvc2
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 500Mi


