apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistence1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: 'D:\tmp1'
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistence2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: 'D:\tmp2'
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain