apiVersion: v1
kind: Pod
metadata:
  name: pod1-with-both-request-limits-3
  labels:
    type: frontend
spec:
  containers:
    - name: httpd-container
      image: httpd
      resources:
        requests:
          memory: 1Gi
          cpu: "100m"
        limits:
          memory: 1Gi
          cpu: "100m"
  priorityClassName: high-priority
  nodeSelector:
    size: large
