######### kubectl create -f pod-defination.yaml ############################
apiVersion: v1
kind: Pod
metadata: 
  name: pod1-without-limits
  labels:
    type: frontend
spec:
  containers:
    - name: httpd-container
      image: httpd