apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: # Set type to ClusterIP
  selector:
   # Add matching labels for mongodb deployment
  ports:
  - targetPort: # Set it to 27017, because mongodb listens on 27017 by default 
    port: # Set any port number for service