apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gke-ingress
spec:
 defaultBackend:
    service:
      name: fleetman-webapp
      port:
        number: 80
 rules:
  - http:
      paths:
      - path: /webapp
        pathType: Prefix
        backend:
          service:
            name: fleetman-webapp
            port:
              number: 80
  - http:
        paths:
          - pathType: Prefix
            path: /queue
            backend:
              service: 
                name: fleetman-queue
                port:
                 number: 8161
        
