kubectl delete configmap app-configmap
kubectl delete secret mongodb-secret
kubectl delete deployment nodeapp
kubectl delete statefulset mongo
kubectl delete service mongodb-h
kubectl delete service node-service
kubectl delete pvc mongo-pvc1
kubectl delete pv mongo-persistence1
kubectl delete pv mongo-persistence2