apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  completions: 9
  parallelism: 3
  backoffLimit: 3
  template:
    metadata:
      name: myjob
    spec:
      containers:
      - name: myjob
        image: ubuntu
        command: ["/bin/sh"]
        args: ["-c", "'expr','3','+','2'","sleep 3"]
      restartPolicy: Never