apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo2
  name: demo2
spec:
  containers:
  - image: docker.io/nginx
    name: demo1
    securityContext:
     runAsNonRoot: true
     runAsUser: 20000
     readOnlyRootFilesystem: true
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
