######### kubectl create -f pod-defination.yaml ############################
apiVersion: v1
kind: Pod
metadata: 
  name: frontend
  labels:
    type: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx