apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    type: frontend
spec:
  containers:
    - name: redis
      image: redis
      env:
        - name: location
          value: us
        - name: backgroundcolor
          value: blue         