apiVersion: v1
kind: Pod
metadata:
  name: myapp-config-pod
  labels:
    name: myapp
spec:
  containers:
  - name: httpd
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: COLOR
      valueFrom:
        configMapKeyRef:
          name:  app-config-new
          key: APP_COLOR

