apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    type: loabbalancer-rs
spec:
  replicas: 3
  selector: 
    matchLabels:
      type: loadbalancer
  template:
    metadata:
      name: nginx-app
      labels:
        type: loadbalancer
    spec:
      containers:
        - name: nginx-container
          image: nginx:xxxx
