apiVersion: v1
kind: Pod
metadata:
  name: pod-security-context
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: ubuntu-container
      image: ubuntu
      command: ["sleep","20"]
