apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo4
  name: demo4
spec:
  containers:
  - args:
    - sleep
    - "100000"
    image: busybox
    name: demo4
    resources: {}
    securityContext:
     runAsNonRoot: true
