apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo2
  name: demo2
spec:
  securityContext:
   runAsUser: 1000
   runAsGroup: 2000
   fsGroup: 3000
  containers:
  - args:
    - sleep
    - "100000"
    image: busybox
    name: demo2
    resources: {}
