apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: readiness-test
spec:
  containers:
  - name: httpd
    image: httpd
    readinessProbe:
      exec:
        command:
        - cat
        - /usr/local/apache2/htdocs/index.html
      initialDelaySeconds: 3
      periodSeconds: 2