apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-routing
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: vehicle.technoavengers.click
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service: 
                name: fleetman-webapp
                port:
                 number: 80
